### ISSUE TITLE
Configurable user-agent

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-cloudflare#514] opened 2023-10-10 13:55 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The work has been done here:
https://github.com/cloudflare/terraform-provider-cloudflare/pull/2816

Consider adopting this as a patch.

**Comment by mikhailshilkov** [comment] 2023-10-11 18:42
Dupe of https://github.com/pulumi/pulumi-cloudflare/issues/179

**Closed by mikhailshilkov** 2023-10-11 18:42 UTC
Labels: size/S, kind/enhancement, resolution/duplicate
