### ISSUE TITLE
Importing RuleSet does not import rules and try to replace

### ISSUE THREAD

**Issue by ami-descope** [pulumi/pulumi-cloudflare#554] opened 2023-11-07 00:51 UTC
### What happened?

I import a ruleset for WAF successfuly, now when I run pulumi up again it wants to replace it, but its exists so it fails

importing
❯ pulumi import cloudflare:index/ruleset:Ruleset domain-rate-limit zones/b0568fbe68169ce1aec3c6f82fca4d6b/be7027900a384d6b9a83d67ae4e13f83 --protect=false

```console
  warning: One or more imported inputs failed to validate. This is almost certainly a bug in the `cloudflare` provider. The import will still proceed, but you will need to edit the generated code after copying it into your program.
    warning: cloudflare:index/ruleset:Ruleset resource 'domain-rate-limit' has a problem: Missing required property 'kind': Type of Ruleset to create. Available values: `custom`, `managed`, `root`, `zone`.
    warning: cloudflare:index/ruleset:Ruleset resource 'domain-rate-limit' has a problem: Missing required property 'phase': Point in the request/response lifecycle where the ruleset will be created. Available values: `ddos_l4`, `ddos_l7`, `http_config_settings`, `http_custom_errors`, `http_log_custom_fields`, `http_ratelimit`, `http_request_cache_settings`, `http_request_dynamic_redirect`, `http_request_firewall_custom`, `http_request_firewall_managed`, `http_request_late_transform`, `http_request_origin`, `http_request_redirect`, `http_request_sanitize`, `http_request_sbfm`, `http_request_transform`, `http_response_compression`, `http_response_firewall_managed`, `http_response_headers_transform`, `magic_transit`.
    warning: cloudflare:index/ruleset:Ruleset resource 'domain-rate-limit' has a problem: Missing required property 'name': Name of the ruleset.

Resources:
    = 1 to import

yes...

Resources:
    = 1 imported
    505 unchanged

Duration: 3s

Please copy the following code into your Pulumi application. Not doing so
will cause Pulumi to report that an update will happen on the next update command.

import * as pulumi from "@pulumi/pulumi";
import * as cloudflare from "@pulumi/cloudflare";

const domain_rate_limit = new cloudflare.Ruleset("domain-rate-limit", {
    accountId: "REDUCTED",
    kind: "",
    name: "",
    phase: "",
});
```

worth mentioning that the rules are empty when i check the state after import
```json
 {
        "urn": "urn:pulumi:dev::main-apps::cloudflare:index/ruleset:Ruleset::domain-rate-limit",
        "custom": true,
        "id": "be7027900a384d6b9a83d67ae4e13f83",
        "type": "cloudflare:index/ruleset:Ruleset",
        "inputs": {
          "accountId": "b0568fbe68169ce1aec3c6f82fca4d6b"
        },
        "outputs": {
          "accountId": "REDUCTED",
          "id": "be7027900a384d6b9a83d67ae4e13f83",
          "rules": []
        },
        "parent": "urn:pulumi:dev::main-apps::pulumi:pulumi:Stack::main-apps-dev",
        "provider": "urn:pulumi:dev::main-apps::pulumi:providers:cloudflare::default_5_12_0::8637ac28-cfcd-4e30-b76f-26129f4484b9",
        "created": "2023-11-07T00:48:32.997955Z",
        "modified": "2023-11-07T00:48:32.997955Z"
      }
```
running pulumi up
```
+-cloudflare:index/ruleset:Ruleset: (replace)
        [id=be7027900a384d6b9a83d67ae4e13f83]
        [urn=urn:pulumi:dev::main-apps::cloudflare:index/ruleset:Ruleset::domain-rate-limit]
        [provider=urn:pulumi:dev::main-apps::pulumi:providers:cloudflare::default_5_12_0::8637ac28-cfcd-4e30-b76f-26129f4484b9]
      - accountId  : "[secret]"
      + description: output<string>
      ~ id         : "be7027900a384d6b9a83d67ae4e13f83" => output<string>
      + kind       : "zone"
      + name       : "domain-rate-limit"
      + phase      : "http_ratelimit"
      ~ rules      : [
          + [0]: {
                  + action     : "block"
                  + description: "default - 100/min"
                  + enabled    : true
                  + expression : "(ends_with(http.host, \"domain.com\") and http.host ne \"random.domain.com\" and not starts_with(http.request.uri.path, \"/.well-known\") and not starts_with(http.request.uri.path, \"/scim\") and not any(http.request.headers[\"x-sdk-go-version\"][*] contains \".\") and not any(http.request.headers[\"x-sdk-python-version\"][*] contains \".\") and not any(http.request.headers[\"x-sdk-node-version\"][*] contains \".\"))"
                  + id         : output<string>
                  + lastUpdated: output<string>
                  + ratelimit  : {
                      + characteristics  : [
                      +     [0]: "cf.unique_visitor_id"
                      +     [1]: "cf.colo.id"
                        ]
                      + mitigationTimeout: 60
                      + period           : 60
                      + requestsPerPeriod: 100
                      + requestsToOrigin : true
                    }
                  + ref        : output<string>
                  + version    : output<string>
                }
        ]
      + zoneId     : [secret]
```

### Example

```ts
new cloudflare.Ruleset("domain-rate-limit", {
        name: "domain-rate-limit",
        kind: "zone",
        phase: "http_ratelimit",
        zoneId: config.cloudflareZoneId,
        rules: [
            {
                action: "block",
                ratelimit: {
                    characteristics: ["cf.unique_visitor_id", "cf.colo.id"],
                    period: 60,
                    requestsPerPeriod: 100,
                    mitigationTimeout: 60,
                    requestsToOrigin: true,
                },
                // expression: `(ends_with(http.host, ${config.zoneDomainName}) and http.host ne "console.${config.zoneDomainName})" and not starts_with(http.request.uri.path, "/.well-known") and not starts_with(http.request.uri.path, "/scim") and not any(http.request.headers["x-sdk-go-version"][*] contains ".") and not any(http.request.headers["x-sdk-python-version"][*] contains ".") and not any(http.request.headers["x-sdk-node-version"][*] contains "."))`,
                expression: `(ends_with(http.host, "domain.com") and http.host ne "random.domain.com" and not starts_with(http.request.uri.path, "/.well-known") and not starts_with(http.request.uri.path, "/scim") and not any(http.request.headers["x-sdk-go-version"][*] contains ".") and not any(http.request.headers["x-sdk-python-version"][*] contains ".") and not any(http.request.headers["x-sdk-node-version"][*] contains "."))`,
                description: "default - 100/min",
                enabled: true,
            },
        ],
    });
```

### Output of `pulumi about`

pulumi about
CLI
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.6
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.5.1'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment] 2023-11-13 10:35
Sorry for a long delay with response, I needed to change the setup of my Cloudflare test account.

I was able to reproduce the error. I used this sample program to provision a ruleset:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as cloudflare from "@pulumi/cloudflare";

const example = new cloudflare.Zone("example", {
    accountId: "<account id>",
    zone: "test-mikhail-example.com",
});

new cloudflare.Ruleset("domain-rate-limit", {
    zoneId: example.id,
    name: "transform rule for URI path",
  description: "change the URI path to a new static path",
  kind: "zone",
  phase: "http_request_transform",

  rules: [{
    action: "rewrite",
    actionParameters: {
      uri: {
        path: {
          value: "/my-new-route"
        }
      }
    },

    expression: "(http.host eq \"example.com\" and http.request.uri.path eq \"/old-path\")",
    description: "example URI path transform rule",
    enabled: true,
  }]
});
```

and then imported the same ruleset. I got the same result. It looks like we get an almost entirely empty state from the Read operation:

```
Marshaling property for RPC[newState]: accountId={<account id>}
Marshaling property for RPC[newState]: id={<ruleset id>}
Marshaling property for RPC[newState]: rules={[]}
```

is all I can see.

Something is odd on our side here, needs further debugging. Note that this is a TFPF resource.

**Comment by ami-descope** [comment] 2023-11-13 13:25
@mikhailshilkov here is the reponse i got from the terraform provider issue i opened

it's not a terraform issue.

https://github.com/cloudflare/terraform-provider-cloudflare/issues/2915

**Comment by ami-descope** [comment] 2023-11-13 13:26
and just to make this even weirder, you can actually apply the resource with rules, but when deleted from state and reimported its missing the rules

**Comment by ami-descope** [comment] 2023-12-14 13:38
@mikhailshilkov there is no milestone set or issue assigned to someone, can we please get an update on this?

**Comment by zbuchheit** [comment] 2024-03-28 17:46
when I attempt this now on the latest version I get `panic: fatal: An assertion has failed: Missing key: responses` when attempting to import

**Comment by zbuchheit** [comment] 2024-03-28 18:14
interestingly, when I run it with --diff I get a different panic `panic: fatal: An assertion has failed: Missing key: autominifies`

**Comment by t0yv0** [comment] 2024-03-28 20:06
CC @iwahbe - the PF implementation was calling into tfbridge.ExtractInputsFromOutputs for import to avoid implementing this functionality natively.

https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pf/tfbridge/provider_read.go#L84 - I recall having some suspicions around this, but don't have a ready explanation for the panic here.

**Comment by mikhailshilkov** [comment] 2024-03-29 09:47
I think the original problem was partially fixed by https://github.com/pulumi/pulumi-terraform-bridge/pull/1659 (that got pulled in 5.20.0 of the provider), but now it replaced the original issue with a panic that we need to solve.

**Comment by mikhailshilkov** [comment] 2024-03-29 09:51
> An assertion has failed: Missing key: responses

The original field is called `response` [here](https://github.com/cloudflare/terraform-provider-cloudflare/blob/bf146186813ead27c49e61df587d32a383d72360/internal/framework/service/rulesets/schema.go#L424)

> Missing key: autominifies

The original field is called `autominify` [here](https://github.com/cloudflare/terraform-provider-cloudflare/blob/bf146186813ead27c49e61df587d32a383d72360/internal/framework/service/rulesets/schema.go#L446)

It looks like we are butchering plural-singular translation.

**Comment by iwahbe** [comment] 2024-03-29 11:45
I have successfully reproduced the panic with this pulumi program and pulumi-cloudflare v5.24.0:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as cloudflare from "@pulumi/cloudflare";

const zone = cloudflare.getZoneOutput({
  accountId: new pulumi.Config().require("cloudflare-account-id"),
  name: "pulumi-cloudflare-demo.com",
})

const ruleset = new cloudflare.Ruleset("domain-rate-limit", {
  name: "domain-rate-limit",
  kind: "zone",
  zoneId: zone.zoneId,
  phase: "http_request_transform",

  rules: [{
    action: "rewrite",
    actionParameters: {
      uri: {
        path: {
          value: "/my-new-route"
        }
      }
    },

    expression: "(http.host eq \"example.com\" and http.request.uri.path eq \"/old-path\")",
    description: "example URI path transform rule",
    enabled: true,
  }],
});

export const importName = pulumi.interpolate`zone/${zone.id}/${ruleset.id}`;

cloudflare.Ruleset.get("imported", importName);
```

For Pulumi employees, the keys necessary to repro are in `providers.all` (ESC).

**Comment by iwahbe** [comment] 2024-04-01 10:34
Keeping open until the bridge release that contains the fix is released as part of pulumi-cloudflare.

**Closed** 2024-04-02 16:09 UTC
Labels: resolution/fixed, kind/bug, p1, customer/feedback, area/import
