### ISSUE TITLE
Cloudflare provider wants to delete and recreate record (without apparent changes), then fia

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi-cloudflare#272] opened 2022-07-21 09:18 UTC
### What happened?

I tried to run "pulumi up" such that cloudflare records would NOT be modified.
Pulumi still wants to delete and recreate all records. 

### Steps to reproduce

I have not been able to reproduce the problem; it does not appear on other stacks of the same projects. Stack state looks clean, but don't want to post it here because of too much sensitive information. I'm happy to provide parts of it on request.

### Expected Behavior

No changes detected.

### Actual Behavior

Changes have been detected, delete-replaces have been planned, which failed.

### Versions used

CLI
Version      3.36.0
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.12.0
azure-native  1.67.0
azuread       4.3.0
azuredevops   2.4.0
cloudflare    4.9.0
docker        3.2.0
dotnet        unknown
kubernetes    3.20.0
mysql         3.1.0
rabbitmq      3.2.0
random        4.8.0
tls           4.6.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='6.0.202'

Current Stack: prodstack

TYPE                                                                   URN

<< resources >>

Found no pending operations associated with prodstack

Backend
Name           DEVB
URL            file://.
User           DEVB\krali
Organizations

Dependencies:
NAME                           VERSION
Microsoft.AspNetCore.Identity  2.2.0
[redacted].Common              6.0.7868

Pulumi locates its logs in C:\Users\krali\AppData\Local\Temp by default

### Additional context

When asking for details, it does not show any apparent changes:

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:prodstack::[redacted]::pulumi:pulumi:Stack::[redacted]-prodstack]
                --cloudflare:index/record:Record: (delete-replaced)
                    [id=[redacted - correct record id]]
                    [urn=urn:pulumi:prodstack::[redacted]::pulumi:providers:kubernetes$k8sx:external-ingresscontroller$cfx:registration$cloudflare:index/record:Record::cf-[redacted].[redacted].net-record]
                    [provider=urn:pulumi:prodstack::[redacted]::pulumi:providers:cloudflare::cloudflare-[redacted]::b940bcb5-c342-4881-ae13-2e5ebda4ef6c]
                +-cloudflare:index/record:Record: (replace)
                    [id=[redacted - correct record id]]
                    [urn=urn:pulumi:prodstack::[redacted]::pulumi:providers:kubernetes$k8sx:external-ingresscontroller$cfx:registration$cloudflare:index/record:Record::cf-[redacted].[redacted].net-record]
                    [provider=urn:pulumi:prodstack::[redacted]::pulumi:providers:cloudflare::cloudflare-[redacted]::b940bcb5-c342-4881-ae13-2e5ebda4ef6c]
                  ~ allowOverwrite: false => false
                  ~ name          : "[redacted]" => "[redacted]"
                  ~ proxied       : true => true
                  ~ type          : "CNAME" => "CNAME"
                  ~ value         : "[redacted].[redacted].net" => "[redacted].[redacted].net"
                  ~ zoneId        : "[redacted - correct zone id]" => "[redacted - correct zone id]"
                ++cloudflare:index/record:Record: (create-replacement)
                    [id=[redacted - correct record id]]
                    [urn=urn:pulumi:prodstack::[redacted]::pulumi:providers:kubernetes$k8sx:external-ingresscontroller$cfx:registration$cloudflare:index/record:Record::cf-[redacted].[redacted].net-record]
                    [provider=urn:pulumi:prodstack::[redacted]::pulumi:providers:cloudflare::cloudflare-[redacted]::b940bcb5-c342-4881-ae13-2e5ebda4ef6c]
                  ~ allowOverwrite: false => false
                  ~ name          : "[redacted]" => "[redacted]"
                  ~ proxied       : true => true
                  ~ type          : "CNAME" => "CNAME"
                  ~ value         : "[redacted].[redacted].net" => "[redacted].[redacted].net"
                  ~ zoneId        : "[redacted - correct zone id]" => "[redacted - correct zone id]"
```
("true" and "false" are red/green here)

I _really_ don't want to do this because this is production. As a last resort, however, I've tried it on a less important service and it still failed:
```

Do you want to perform this update? yes

Updating (prodstack):
     Type                                   Name                               Status                   Info
     pulumi:pulumi:Stack                    [redacted]-prodstack                        **failed**               1 error
     └─ pulumi:providers:kubernetes         flatten-k8s-PROD                                            [diff: ~version]
        └─ k8sx:external-ingresscontroller  backend
           └─ cfx:registration              cf-[redacted].[redacted].net
 +-           └─ cloudflare:index:Record    cf-[redacted].[redacted].net-record  **replacing failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack ([redacted]-prodstack):
    error: update failed

  cloudflare:index:Record (cf-[redacted].[redacted].net-record):
    error: deleting urn:pulumi:prodstack::[redacted]::pulumi:providers:kubernetes$k8sx:external-ingresscontroller$cfx:registration$cloudflare:index/record:Record::cf-[redacted].[redacted].net-record: 1 error occurred:
        * error deleting Cloudflare Record: HTTP status 400: Could not route to /zones/dns_records/[redacted - correct record id], perhaps your object identifier is invalid? (7003), No route for that URI (7000)
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kralikba** [comment] 2022-07-21 12:32
Downgrading Pulumi.Cloudflare to 3.5.0 seems to fix the problem. Moving back up to 4.0.0 causes the issue to reappear.

**Comment by stack72** [comment] 2022-07-25 11:23
Hi @kralikba 

Please can you try and provide a set of code that helps me to reproduce the problem?

Paul

**Comment by kralikba** [comment] 2022-07-26 14:44
> Hi @kralikba
> 
> Please can you try and provide a set of code that helps me to reproduce the problem?
> 
> Paul

I have not yet been able to reproduce the issue on a minimal part of the system.
Do you have any idea how the zoneId could become empty/null in the request URL? (as per the last line of pulumi's output in my error description). Adding a debugging proxy between the provider and the cloudflare web service (using Fiddler) confirms that somehow the request path is wrong. Even more, it is shown to be `/zones//dns_records/[redacted - correct record id]` (note the `//`, between which the zone id should be seen).

**Comment by yz89122** [comment] 2023-03-26 08:34
same issue here: https://github.com/pulumi/pulumi-cloudflare/issues/325

**Comment by mikhailshilkov** [comment] 2023-07-28 12:59
Since no repro was originally provided, I'll assume it's a duplicate of #325

**Closed by mikhailshilkov** 2023-07-28 12:59 UTC
Labels: awaiting-upstream, kind/bug, resolution/duplicate
