### ISSUE TITLE
ZoneSettingsOverrideSettingsArgs.tls13 should accept value "zrt"

### ISSUE THREAD

**Issue by zhangyoufu** [pulumi/pulumi-cloudflare#339] opened 2023-02-17 12:40 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`ZoneSettingsOverrideSettingsArgs.tls13` controls whether TLSv1.3 should be supported.
It accepts value `on` or `off`. It should accept value `zrt` as well, which means `Enabled+0RTT`.
This feature was implemented in terraform provider. See https://github.com/cloudflare/terraform-provider-cloudflare/issues/106.

**Comment by AaronFriel** [comment] 2023-02-20 19:32
@zhangyoufu Thanks for filing this. Which version of the provider are you using? It looks like the `tls13` input property of a `ZoneSettingsOverrideSettingsArgs` is a string property. Did you encounter an error trying to use the value `"zrt"`?

**Comment by zhangyoufu** [comment] 2023-02-21 03:34
> Which version of the provider are you using?

4.15.0

> Did you encounter an error trying to use the value `"zrt"`?

Yes.
```
error: cloudflare:index/zoneSettingsOverride:ZoneSettingsOverride resource 'example' has a problem: Invalid or unknown key. Examine values at 'ZoneSettingsOverride.Settings.Tls13'.
```

**Comment by AaronFriel** [comment] 2023-02-21 06:14
Would you copy the error you received and if possible, provide a minimal complete program to reproduce it?

It greatly helps us to start from a program that reproduces the issue.

**Comment by zhangyoufu** [comment] 2023-02-21 07:34
> the error you received

```
Diagnostics:
  cloudflare:index:ZoneSettingsOverride (example):
    error: cloudflare:index/zoneSettingsOverride:ZoneSettingsOverride resource 'example' has a problem: Invalid or unknown key. Examine values at 'ZoneSettingsOverride.Settings.Tls13'.
```

> a minimal complete program to reproduce it

```python
import pulumi
import pulumi_cloudflare as cloudflare

config = pulumi.Config()

zone = cloudflare.Zone('example',
    account_id=config.require('cloudflare_account_id'),
    zone='example.com',
)

cloudflare.ZoneSettingsOverride('example',
    zone_id=zone.id,
    settings=cloudflare.ZoneSettingsOverrideSettingsArgs(
        # BUG: tls13 reports invalid or unknown key, see https://github.com/pulumi/pulumi-cloudflare/issues/166
        # BUG: zrt is not implemented by Pulumi, see https://github.com/pulumi/pulumi-cloudflare/issues/339
        tls13='zrt', # TLS 1.3
    ),
)
```

**Comment by AaronFriel** [comment] 2023-02-21 23:05
Thanks for the code snippet along with the exact error. I think I see the issue here, we're translating the key `tls13` incorrectly in sending it to the underlying provider. We'll look into this!

**Comment by AaronFriel** [comment] 2023-02-21 23:06
This is a duplicate of #166 and the underlying error is in the bridge, so I'm closing this and updating #166 for us to re-triage.

**Closed by AaronFriel** 2023-02-21 23:06 UTC
Labels: kind/enhancement
