### ISSUE TITLE
Cloudflare:index:Record missing required argument

### ISSUE THREAD

**Issue by stefaneacsu147** [pulumi/pulumi-cloudflare#304] opened 2022-11-25 10:34 UTC
### What happened?

I set up to use apiToken instead of the [legacy way](https://www.pulumi.com/registry/packages/cloudflare/installation-configuration/) from api_key, email variant and I get the following error when trying to update the index record(s).

```
cloudflare:index:Record (ingress-stable-protected-iap-CNAME-chat.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-A-record):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-CNAME-*.qa.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-CNAME-*.ci.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-churn-protected-iap-A-record):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-public-CNAME-*.sandbox.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-CNAME-*.rc.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-public-CNAME-*.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-churn-protected-iap-CNAME-*.dev.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-CNAME-*.stag.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-stable-protected-iap-CNAME-*.prod.g.nakhoda.ai):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

  cloudflare:index:Record (ingress-churn-public-A-record):
    error: Preview failed: could not validate provider configuration: 5 errors occurred:
        * Missing required argument: "email": all of `api_key,email` must be specified
        * Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
        * Invalid or unknown key

```

I have setup cfConfig with the correct values:
```
cloudflare: {
                apiKey: cfConfig.requireSecret("apiToken"),
                email: "EMAIL"
            }
```

For CertManager or TLS certificates it goes through with no problems but it seems for the ingress controller it complains that is missing which is not since apiToken should contain all the information as described by the docs so it is that not updated properly for these type of resources?

**Comment by danielrbradley** [comment] 2022-11-29 14:29
Thanks for getting in touch @stefaneacsu147 

Would you be able to provide a complete example of the code (excluding any personal details) which reproduces the errors you're seeing above so we can see how you're configuring the provider and the resource?

**Comment by kly630** [comment] 2022-12-02 03:05
This same error is happening to me with project that previously deployed successfully 10 days ago and is now failing on preview.  `Diagnostics:
  pulumi:pulumi:Stack (kong-post-qa-gcloud-us-east4):
    W1202 02:30:30.845242     498 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
    To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

    warning: provider config warning: Use resource specific `account_id` attributes instead.
    warning: provider config warning: Use resource specific `account_id` attributes instead.
    error: Error: invocation of cloudflare:index/getZones:getZones returned an error: could not validate provider configuration: 4 errors occurred:
    	* Invalid combination of arguments: "api_token": one of `api_key,api_token,api_user_service_key` must be specified
    	* Missing required argument: "email": all of `api_key,email` must be specified
    	* Invalid combination of arguments: "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
    	* Invalid combination of arguments: "api_key": one of `api_key,api_token,api_user_service_key` must be specified
    
    
        at Object.callback (/home/circleci/project/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/home/circleci/project/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/circleci/project/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/circleci/project/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/circleci/project/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (internal/process/task_queues.js:79:11)`

I am setting the following environment variables in my project `CLOUDFLARE_ACCOUNT_ID=<redacted>
CLOUDFLARE_EMAIL=<redacted>
CLOUDFLARE_API_KEY=<redacted>`

I am using the following in my typescript project
"dependencies": {
    "@pulumi/aiven": "^4.2.1",
    "@pulumi/aws": "^4.25.0",
    "@pulumi/cloudflare": "^4.0.0",
    "@pulumi/gcp": "^5.25.0",
    "@pulumi/pulumi": "^3.16.0",
    "axios": "^0.19.2"
  }

I do believe a recently release here has caused this issue.  I'm likely going to try downgrading tomorrow.

**Comment by danielrbradley** [comment] 2022-12-02 20:31
According to the diff based on the last version upgrade, there's only a minor env validation change I could see: https://github.com/cloudflare/terraform-provider-cloudflare/compare/v3.24.0...v3.29.0#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22L105

**Comment by kly630** [comment] 2022-12-03 15:09
> According to the diff based on the last version upgrade, there's only a minor env validation change I could see: [cloudflare/terraform-provider-cloudflare@v3.24.0...v3.29.0#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22L105](https://github.com/cloudflare/terraform-provider-cloudflare/compare/v3.24.0...v3.29.0#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22L105)
> 
> If you're able to narrow down which was the last working version we should be able to isolate the associated change causing the issue.

I was able to get a successful pulumi preview by pinning the cloudflare provider to 4.12.1. So something about 4.13.0 definitely caused me to receive this error this week.  I almost forgot I was taking compatible version in my project.  

An employee on my team suggested we might have picked up a regression from the terraform provider.  https://github.com/cloudflare/terraform-provider-cloudflare/issues/1919

That said, I at least wanted to report back that 4.12.1 works for me on my current settings.

**Comment by mattfysh** [comment] 2023-05-17 07:02
@stefaneacsu147 I think you're not supposed to specify email when using an api token, I had this error and managed to get around it by defining API token only.

**Comment by omidraha** [comment] 2023-07-06 00:20
I got this error:

```bash
Diagnostics:
  pulumi:pulumi:Stack (devops-dev):
    error: update failed

  cloudflare:index:Record (record):
    error: 1 error occurred:
    	* failed to create DNS record: Authentication error (10000)

```
Info:

```python
import pulumi
import pulumi_aws as aws
import pulumi_cloudflare as cloudflare

def create_certificate():
    """
    Create Certificate for primary domain and wild subdomain
    """
    certificate = aws.acm.Certificate(
        resource_name="cert",
        domain_name="example.com",
        validation_method="DNS",
        subject_alternative_names=["*.example.com"]
    )
    return certificate


def create_cloudflare(certificate):
    """
        Create a Cloudflare Record
    """
    record = cloudflare.Record(
        "record",
        type="CNAME",
        name=certificate.domain_validation_options[0].resource_record_name,
        value=certificate.domain_validation_options[0].resource_record_value,
        zone_id='***'
    )
    return record
```

```bash
pulumi up
export CLOUDFLARE_EMAIL="mail@example.com"
export CLOUDFLARE_API_KEY="***"
except CLOUDFLARE_ACCOUNT_ID="***"
```

Any help?

**Comment by mattfysh** [comment] 2023-07-06 02:35
@omidraha see comment above

**Comment by mikhailshilkov** [comment] 2023-07-28 13:15
Thank you @mattfysh for the suggestion. Since nobody said it doesn't work, I'll go ahead and close this issue. Please report back if I'm wrong here.

**Closed by mikhailshilkov** 2023-07-28 13:15 UTC
Labels: kind/bug, resolution/by-design
